using System.Security.AccessControl;
using System.Security.Cryptography;
using System.Security.Principal;
using System.Text;

namespace VictoryLauncher;

/// <summary>
/// Kernel 100 §9-11: the Windows equivalent of packaging/podman/generate-env.sh.
/// Asks only the two questions §9 allows (lot name, Operator handle),
/// generates everything else, and never asks the user to hand-edit a
/// config file. Slugify/secret-generation logic is deliberately kept
/// equivalent to generate-env.sh's, even though nothing reads both --
/// the two are independent implementations of the same contract the
/// backend itself defines, not literally shared code.
/// </summary>
internal static class EnvGenerator
{
    public sealed record FirstRunAnswers(string LotName, string OperatorHandle, string TunnelMode);

    public static bool EnvFileExists() => File.Exists(AppPaths.EnvFile);

    /// <summary>
    /// Parsed back out by RuntimeManager to build the backend process's
    /// own environment at launch time -- this file is the single source
    /// of truth for POSTGRES_PASSWORD/OPERATOR_HANDLE/etc., not duplicated
    /// state kept in memory across launcher restarts.
    /// </summary>
    public static Dictionary<string, string> ReadAll()
    {
        var values = new Dictionary<string, string>();
        foreach (var line in File.ReadAllLines(AppPaths.EnvFile))
        {
            var trimmed = line.Trim();
            if (trimmed.Length == 0 || trimmed.StartsWith('#'))
                continue;
            var separatorIndex = trimmed.IndexOf('=');
            if (separatorIndex <= 0)
                continue;
            values[trimmed[..separatorIndex]] = trimmed[(separatorIndex + 1)..];
        }
        return values;
    }

    public static void Generate(FirstRunAnswers answers)
    {
        var lotName = answers.LotName.Trim();
        var operatorHandle = answers.OperatorHandle.Trim();
        if (lotName.Length == 0)
            throw new ArgumentException("a lot name is required");
        if (operatorHandle.Length == 0)
            throw new ArgumentException("an Operator handle is required");

        var locationSlug = Slugify(lotName);
        if (locationSlug.Length == 0)
            throw new ArgumentException($"could not derive a usable slug from '{lotName}' -- try a name with at least one letter or digit");

        AppPaths.EnsureDataDirectoriesExist();

        var postgresPassword = GenerateSecret();

        var lines = new[]
        {
            $"# Generated by VictoryLauncher on {DateTime.UtcNow:yyyy-MM-ddTHH:mm:ssZ}.",
            "# This file is created fresh per install and is never checked into",
            "# version control -- treat it as a machine secret.",
            $"POSTGRES_PASSWORD={postgresPassword}",
            // Plain Windows paths -- unlike the Podman-era .env, nothing
            // here ever gets fed through a container bind-mount syntax.
            // The backend runs as a native Windows process now and reads
            // these with Go's platform-aware path/filepath, same as it
            // reads Linux paths on the server.
            $"STORAGE_ROOT={AppPaths.StorageDir}",
            $"BACKUP_DIR={AppPaths.BackupDir}",
            $"EXPORTS_ROOT={AppPaths.ExportsDir}",
            $"OPERATOR_HANDLE={operatorHandle}",
            $"DEFAULT_LOCATION_SLUG={locationSlug}",
            $"DEFAULT_LOCATION_NAME={lotName}",
            // "off" or "quick" -- asked as the first-run wizard's third
            // question, right alongside lot name/handle, not decided
            // silently. See RuntimeSetup for what each mode does.
            $"TUNNEL_MODE={answers.TunnelMode}",
            // "automatic" or "off" -- unlike TUNNEL_MODE, not asked at
            // first run (Grant: opt-out belongs in Status, not as a
            // fourth wizard question). See UpdateChecker for what each
            // mode does and how backend-changing updates are scheduled.
            "UPDATE_MODE=automatic",
        };

        File.WriteAllText(AppPaths.EnvFile, string.Join("\n", lines) + "\n", new UTF8Encoding(false));
        RestrictToCurrentUserAndAdministrators(AppPaths.EnvFile);
    }

    /// <summary>
    /// Used by Status to change remote-access mode after first run --
    /// Generate only ever runs once (the wizard), but this is something
    /// an Operator reasonably changes later (e.g. turning Quick Tunnel on
    /// after initially declining it). Rewrites just the known keys, not
    /// the whole first-run flow.
    /// </summary>
    public static void UpdateTunnelMode(string tunnelMode)
    {
        var values = ReadAll();
        values["TUNNEL_MODE"] = tunnelMode;
        var lines = values.Select(kv => $"{kv.Key}={kv.Value}");
        File.WriteAllText(AppPaths.EnvFile, string.Join("\n", lines) + "\n", new UTF8Encoding(false));
        RestrictToCurrentUserAndAdministrators(AppPaths.EnvFile);
    }

    /// <summary>"automatic" or "off" -- the Operator opt-out, changeable from Status.</summary>
    public static void UpdateUpdateMode(string updateMode)
    {
        var values = ReadAll();
        values["UPDATE_MODE"] = updateMode;
        var lines = values.Select(kv => $"{kv.Key}={kv.Value}");
        File.WriteAllText(AppPaths.EnvFile, string.Join("\n", lines) + "\n", new UTF8Encoding(false));
        RestrictToCurrentUserAndAdministrators(AppPaths.EnvFile);
    }

    /// <summary>
    /// Mirrors generate-env.sh's `tr '[:upper:]' '[:lower:]' | tr -s ' ' '-' | tr -cd 'a-z0-9-'`.
    /// </summary>
    internal static string Slugify(string lotName)
    {
        var lowered = lotName.ToLowerInvariant();
        var builder = new StringBuilder(lowered.Length);
        var lastWasHyphen = false;
        foreach (var ch in lowered)
        {
            if (ch is >= 'a' and <= 'z' or >= '0' and <= '9')
            {
                builder.Append(ch);
                lastWasHyphen = false;
            }
            else if (ch == ' ' || ch == '-')
            {
                if (!lastWasHyphen && builder.Length > 0)
                {
                    builder.Append('-');
                    lastWasHyphen = true;
                }
            }
            // anything else (punctuation, unicode) is dropped, matching -cd 'a-z0-9-'
        }
        return builder.ToString().Trim('-');
    }

    /// <summary>32 bytes of real randomness, matching generate-env.sh's `openssl rand -base64 32`.</summary>
    private static string GenerateSecret()
    {
        var bytes = RandomNumberGenerator.GetBytes(32);
        return Convert.ToBase64String(bytes).Replace("=", "").Replace("+", "").Replace("/", "");
    }

    /// <summary>
    /// K100 §10 "appropriately permissioned": strips inherited ACEs and
    /// grants FullControl only to the current user and Administrators, so
    /// other accounts on a shared Windows machine can't read the Postgres
    /// password out of %ProgramData%.
    /// </summary>
    private static void RestrictToCurrentUserAndAdministrators(string path)
    {
        var fileInfo = new FileInfo(path);
        var security = new FileSecurity();
        security.SetAccessRuleProtection(true, false); // disable inheritance, drop inherited rules

        var currentUser = WindowsIdentity.GetCurrent().User;
        if (currentUser is not null)
        {
            security.AddAccessRule(new FileSystemAccessRule(currentUser, FileSystemRights.FullControl, AccessControlType.Allow));
        }
        var administrators = new SecurityIdentifier(WellKnownSidType.BuiltinAdministratorsSid, null);
        security.AddAccessRule(new FileSystemAccessRule(administrators, FileSystemRights.FullControl, AccessControlType.Allow));

        fileInfo.SetAccessControl(security);
    }
}
