using System.Security.AccessControl;
using System.Security.Cryptography;
using System.Security.Principal;
using System.Text;

namespace VictoryLauncher;

/// <summary>
/// Kernel 100 §9-11: the Windows equivalent of packaging/podman/generate-env.sh.
/// Asks only the two questions §9 allows (lot name, Operator handle),
/// generates everything else, and never asks the user to hand-edit a
/// config file. Keep this in sync with generate-env.sh's slugify/secret
/// logic -- they must produce compatible .env files, since both feed the
/// same compose.yml contract.
/// </summary>
internal static class EnvGenerator
{
    public sealed record FirstRunAnswers(string LotName, string OperatorHandle);

    public static bool EnvFileExists() => File.Exists(AppPaths.EnvFile);

    public static void Generate(FirstRunAnswers answers)
    {
        var lotName = answers.LotName.Trim();
        var operatorHandle = answers.OperatorHandle.Trim();
        if (lotName.Length == 0)
            throw new ArgumentException("a lot name is required");
        if (operatorHandle.Length == 0)
            throw new ArgumentException("an Operator handle is required");

        var locationSlug = Slugify(lotName);
        if (locationSlug.Length == 0)
            throw new ArgumentException($"could not derive a usable slug from '{lotName}' -- try a name with at least one letter or digit");

        AppPaths.EnsureDataDirectoriesExist();

        var postgresPassword = GenerateSecret();

        var lines = new[]
        {
            $"# Generated by VictoryLauncher on {DateTime.UtcNow:yyyy-MM-ddTHH:mm:ssZ}.",
            "# This file is created fresh per install and is never checked into",
            "# version control -- treat it as a machine secret.",
            $"POSTGRES_PASSWORD={postgresPassword}",
            // Windows compose bind-mounts need forward slashes even on
            // Windows -- Docker/Podman's Windows client accepts the
            // drive-letter form (C:/ProgramData/...) but not backslashes.
            $"STORAGE_ROOT={ToComposePath(AppPaths.StorageDir)}",
            $"BACKUP_DIR={ToComposePath(AppPaths.BackupDir)}",
            $"EXPORTS_ROOT={ToComposePath(AppPaths.ExportsDir)}",
            $"OPERATOR_HANDLE={operatorHandle}",
            $"DEFAULT_LOCATION_SLUG={locationSlug}",
            $"DEFAULT_LOCATION_NAME={lotName}",
        };

        File.WriteAllText(AppPaths.EnvFile, string.Join("\n", lines) + "\n", new UTF8Encoding(false));
        RestrictToCurrentUserAndAdministrators(AppPaths.EnvFile);
    }

    private static string ToComposePath(string windowsPath) => windowsPath.Replace('\\', '/');

    /// <summary>
    /// Mirrors generate-env.sh's `tr '[:upper:]' '[:lower:]' | tr -s ' ' '-' | tr -cd 'a-z0-9-'`.
    /// </summary>
    internal static string Slugify(string lotName)
    {
        var lowered = lotName.ToLowerInvariant();
        var builder = new StringBuilder(lowered.Length);
        var lastWasHyphen = false;
        foreach (var ch in lowered)
        {
            if (ch is >= 'a' and <= 'z' or >= '0' and <= '9')
            {
                builder.Append(ch);
                lastWasHyphen = false;
            }
            else if (ch == ' ' || ch == '-')
            {
                if (!lastWasHyphen && builder.Length > 0)
                {
                    builder.Append('-');
                    lastWasHyphen = true;
                }
            }
            // anything else (punctuation, unicode) is dropped, matching -cd 'a-z0-9-'
        }
        return builder.ToString().Trim('-');
    }

    /// <summary>32 bytes of real randomness, matching generate-env.sh's `openssl rand -base64 32`.</summary>
    private static string GenerateSecret()
    {
        var bytes = RandomNumberGenerator.GetBytes(32);
        return Convert.ToBase64String(bytes).Replace("=", "").Replace("+", "").Replace("/", "");
    }

    /// <summary>
    /// K100 §10 "appropriately permissioned": strips inherited ACEs and
    /// grants FullControl only to the current user and Administrators, so
    /// other accounts on a shared Windows machine can't read the Postgres
    /// password out of %ProgramData%.
    /// </summary>
    private static void RestrictToCurrentUserAndAdministrators(string path)
    {
        var fileInfo = new FileInfo(path);
        var security = new FileSecurity();
        security.SetAccessRuleProtection(true, false); // disable inheritance, drop inherited rules

        var currentUser = WindowsIdentity.GetCurrent().User;
        if (currentUser is not null)
        {
            security.AddAccessRule(new FileSystemAccessRule(currentUser, FileSystemRights.FullControl, AccessControlType.Allow));
        }
        var administrators = new SecurityIdentifier(WellKnownSidType.BuiltinAdministratorsSid, null);
        security.AddAccessRule(new FileSystemAccessRule(administrators, FileSystemRights.FullControl, AccessControlType.Allow));

        fileInfo.SetAccessControl(security);
    }
}
