#!/usr/bin/env bash
# Kernel 100: stand-in for the Windows installer's first-run flow (§9-§11)
# while the actual Velopack-based installer doesn't exist yet. This proves
# out the *logic* (no Grant-specific defaults, generated secrets, real
# persistent paths) on Linux/Podman; the eventual installer reimplements
# this same logic in whatever language the installer itself is written in,
# not by shelling out to this script on a real user's machine.
#
# Deliberately asks only the questions §9 allows: lot name and Operator
# handle. Everything else (password, generated secret, paths) is either
# generated or a sensible non-Grant-specific default the user never has to
# think about.
set -euo pipefail

TARGET_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$TARGET_DIR/.env"
DATA_ROOT="${VICTORY_DATA_ROOT:-$TARGET_DIR/data}"

if [[ -f "$ENV_FILE" ]]; then
  echo "refusing to overwrite existing $ENV_FILE -- delete it first if you really want to regenerate" >&2
  exit 1
fi

read -r -p "What should this Victory lot be called? " LOT_NAME
if [[ -z "$LOT_NAME" ]]; then
  echo "a lot name is required" >&2
  exit 1
fi

read -r -p "What should your Operator handle be? " OPERATOR_HANDLE_VALUE
if [[ -z "$OPERATOR_HANDLE_VALUE" ]]; then
  echo "an Operator handle is required" >&2
  exit 1
fi

# Slugify the lot name the same way a real installer would: lowercase,
# spaces to hyphens, strip anything that isn't alphanumeric/hyphen. This
# is the DEFAULT_LOCATION_SLUG -- a real per-install identifier, not
# victory-theater.
LOCATION_SLUG="$(echo "$LOT_NAME" | tr '[:upper:]' '[:lower:]' | tr -s ' ' '-' | tr -cd 'a-z0-9-')"
if [[ -z "$LOCATION_SLUG" ]]; then
  echo "could not derive a usable slug from '$LOT_NAME' -- try a name with at least one letter or digit" >&2
  exit 1
fi

# 32 bytes of real randomness, not a word list or anything memorable --
# this is a machine credential, not something a human ever types.
POSTGRES_PASSWORD_VALUE="$(openssl rand -base64 32 | tr -d '=+/\n')"

mkdir -p "$DATA_ROOT/storage" "$DATA_ROOT/backups" "$DATA_ROOT/exports"

cat > "$ENV_FILE" <<EOF
# Generated by generate-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# This file is created fresh per install and is never checked into
# version control (see .gitignore) -- treat it as a machine secret.
POSTGRES_PASSWORD=$POSTGRES_PASSWORD_VALUE
STORAGE_ROOT=$DATA_ROOT/storage
BACKUP_DIR=$DATA_ROOT/backups
EXPORTS_ROOT=$DATA_ROOT/exports
OPERATOR_HANDLE=$OPERATOR_HANDLE_VALUE
DEFAULT_LOCATION_SLUG=$LOCATION_SLUG
DEFAULT_LOCATION_NAME=$LOT_NAME
EOF
chmod 600 "$ENV_FILE"

echo "Wrote $ENV_FILE for lot \"$LOT_NAME\" (slug: $LOCATION_SLUG), Operator handle \"$OPERATOR_HANDLE_VALUE\"."
echo "Next: podman compose --env-file '$ENV_FILE' -f '$TARGET_DIR/compose.yml' up -d --build"
