ALTER TABLE messages
  ADD COLUMN IF NOT EXISTS message_type TEXT NOT NULL DEFAULT 'message',
  ADD COLUMN IF NOT EXISTS venue_slug TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS session_id UUID;
